[versions]

androidx-activity = "1.10.1"
androidx-annotation = "1.9.1"
androidx-browser = "1.9.0"
androidx-camera = "1.4.2"
androidx-core = "1.17.0"
androidx-core-splashscreen = "1.0.1"
androidx-compose-bom = "2025.08.01"
androidx-credentials = "1.5.0"
androidx-datastore = "1.1.7"
androidx-exifinterface = "1.4.1"
androidx-hilt-navigation-compose = "1.2.0"
androidx-lifecycle = "2.9.3"
androidx-material = "1.13.0"
androidx-navigation = "2.9.3"
androidx-test-espresso = "3.7.0"
androidx-test-junit = "1.3.0"
androidx-test-uiautomator = "2.3.0"
androidx-webkit = "1.14.0"
androidx-window = "1.4.0"

junit = "4.13.2"

# kotlin
kotlin = "2.2.10"
kotlinx-coroutines-bom = "1.10.2"
ksp = "2.2.10-2.0.2"

# square
leakcanary = "2.14"
moshi = "1.15.2"
okio = "3.16.0"
okhttp-bom = "5.1.0"
retrofit-bom = "3.0.0"

# google services
play-services-location = "21.3.0"
play-services-maps = "19.2.0"
google-android-maps-compose = "6.9.0"
google-android-maps-utils = "3.16.2"
google-libphonenumber = "9.0.13"
google-googleid = "1.1.1"

# dagger/hilt
dagger-hilt = "2.57.1"

accompanist = "0.37.3"
coil-bom = "3.3.0"
facebook = "18.1.3"
timber = "5.0.1"

# Plugins
androidGradlePlugin = "8.13.0"
mapsSecretsPlugin = "2.0.1"

[libraries]

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "androidx-camera" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "androidx-camera" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "androidx-camera" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "androidx-exifinterface" }

androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material3-adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
androidx-compose-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class" }

androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }


androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }

androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "androidx-credentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "androidx-credentials" }

androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }

androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt-navigation-compose" }
androidx-material = { module = "com.google.android.material:material", version.ref = "androidx-material" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "androidx-navigation" }

androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidx-test-uiautomator" }

androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "androidx-webkit" }
androidx-window = { module = "androidx.window:window", version.ref = "androidx-window" }

accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
dagger-hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger-hilt" }
dagger-hilt-compilier = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger-hilt" }
junit = { module = "junit:junit", version.ref = "junit" }

# Kotlin
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlinx-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "kotlinx-coroutines-bom" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" }

# Square
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp-bom" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver" }
okhttp-tls = { module = "com.squareup.okhttp3:okhttp-tls" }
retrofit-bom = { module = "com.squareup.retrofit2:retrofit-bom", version.ref = "retrofit-bom" }
retrofit = { module = "com.squareup.retrofit2:retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi" }

# Google Services
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "play-services-maps" }
google-android-maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "google-android-maps-compose" }
google-android-maps-utils = { module = "com.google.maps.android:android-maps-utils", version.ref = "google-android-maps-utils" }
google-libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "google-libphonenumber" }
google-googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "google-googleid" }

coil-bom = { module = "io.coil-kt.coil3:coil-bom", version.ref = "coil-bom" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose" }
coil-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

facebook-login = { module = "com.facebook.android:facebook-login", version.ref = "facebook" }

[plugins]

android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }

maps-secrets-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "mapsSecretsPlugin" }